// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_uuid_delete from "./routes/admin/[uuid]/delete.tsx";
import * as $admin_uuid_index from "./routes/admin/[uuid]/index.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_new from "./routes/admin/new.tsx";
import * as $index from "./routes/index.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/[uuid]/delete.tsx": $admin_uuid_delete,
    "./routes/admin/[uuid]/index.tsx": $admin_uuid_index,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/new.tsx": $admin_new,
    "./routes/index.tsx": $index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
